[package]
name = "injector-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dll-syringe = { version = "0.13.1", features = ["into-x86-from-x64"] }